---
title: "make_datasets"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load library
```{r}
library(ExtDist)
library(diffpriv)
library(stats)
library(forecast)
library(dplyr)
library(xts)
```

## Original set
```{r}
og <- read.csv('H:/내 드라이브/ShortPaper_sim/Original.csv',header=T)
realset <- og[,7:9]
head(realset)
```

## Make hourly data
```{r}
hZone1<-realset[seq(from=1,to=52416,by=6),1]
hZone2<-realset[seq(from=1,to=52416,by=6),2]
hZone3<-realset[seq(from=1,to=52416,by=6),3]
```

```{r}
NoPerturb <- cbind(hZone1,hZone2,hZone3)

LPAepsilon1 <- read.csv("LPAepsilon1.csv")
LPAepsilon2 <- read.csv("LPAepsilon2.csv")
LPAepsilon3 <- read.csv("LPAepsilon3.csv")
LPAepsilon4 <- read.csv("LPAepsilon4.csv")

FPAepsilon1 <- read.csv("FPAepsilon1.csv")
FPAepsilon2 <- read.csv("FPAepsilon2.csv")
FPAepsilon3 <- read.csv("FPAepsilon3.csv")
FPAepsilon4 <- read.csv("FPAepsilon4.csv")

sFPAepsilon1 <- read.csv("sFPAepsilon1.csv")
sFPAepsilon2 <- read.csv("sFPAepsilon2.csv")
sFPAepsilon3 <- read.csv("sFPAepsilon3.csv")
sFPAepsilon4 <- read.csv("sFPAepsilon4.csv")

tFPAepsilon1 <- read.csv("tFPAepsilon1.csv")
tFPAepsilon2 <- read.csv("tFPAepsilon2.csv")
tFPAepsilon3 <- read.csv("tFPAepsilon3.csv")
tFPAepsilon4 <- read.csv("tFPAepsilon4.csv")
```

```{r}
euclidean <- function(a, b) sqrt(sum((a - b)^2))
```

```{r}
for(i in 1:3){
  for(j in 1:4)
  assign(paste0("euci",i,"j",j),euclidean(NoPerturb[,i],get(paste0("LPAepsilon",j))[,i+1]))
}


for(i in 1:3){
  for(j in 1:4)
  assign(paste0("FPAeuci",i,"j",j),euclidean(NoPerturb[,i],get(paste0("FPAepsilon",j))[,i+1]))
}


for(i in 1:3){
  for(j in 1:4)
  assign(paste0("sFPAeuci",i,"j",j),euclidean(NoPerturb[,i],get(paste0("sFPAepsilon",j))[,i+1]))
}


for(i in 1:3){
  for(j in 1:4)
  assign(paste0("tFPAeuci",i,"j",j),euclidean(NoPerturb[,i],get(paste0("tFPAepsilon",j))[,i+1]))
}
```


```{r}
x<-c(0.48,2.4,4.8,24)
euc1<-c(euci1j1,euci1j2,euci1j3,euci1j4)
euc2<-c(euci2j1,euci2j2,euci2j3,euci2j4)
euc3<-c(euci3j1,euci3j2,euci3j3,euci3j4)

feuc1<-c(FPAeuci1j1,FPAeuci1j2,FPAeuci1j3,FPAeuci1j4)
feuc2<-c(FPAeuci2j1,FPAeuci2j2,FPAeuci2j3,FPAeuci2j4)
feuc3<-c(FPAeuci3j1,FPAeuci3j2,FPAeuci3j3,FPAeuci3j4)

sfeuc1<-c(sFPAeuci1j1,sFPAeuci1j2,sFPAeuci1j3,sFPAeuci1j4)
sfeuc2<-c(sFPAeuci2j1,sFPAeuci2j2,sFPAeuci2j3,sFPAeuci2j4)
sfeuc3<-c(sFPAeuci3j1,sFPAeuci3j2,sFPAeuci3j3,sFPAeuci3j4)

tfeuc1<-c(tFPAeuci1j1,tFPAeuci1j2,tFPAeuci1j3,FPAeuci1j4)
tfeuc2<-c(tFPAeuci2j1,tFPAeuci2j2,tFPAeuci2j3,FPAeuci2j4)
tfeuc3<-c(tFPAeuci3j1,tFPAeuci3j2,tFPAeuci3j3,FPAeuci3j4)
```


```{r}
myeuc<-rbind(Re(euc1),Re(euc2),Re(euc3),Re(feuc1),Re(feuc2),feuc3,sfeuc1,sfeuc2,sfeuc3,tfeuc1,tfeuc2,tfeuc3)
```


